application: maph4ck
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static files
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap-3.2.0-dist

# Font Awesome
- url: /font-awesome
  static_dir: font-awesome-4.1.0

# Bootstrap Social
- url: /bootstrap-social
  static_dir: bootstrap-social

# Public pages
- url: /
  script: maph4ck.application

- url: /trades/recent.*
  script: maph4ck.application

- url: /trade/.*
  script: maph4ck.application

- url: /user/.*
  script: maph4ck.application

- url: /feedback
  script: maph4ck.application

- url: /faq
  script: maph4ck.application

# User pages
- url: /.*
  script: maph4ck.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest